name: e2e-ios

env:
  NO_FLIPPER: 1

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-ios:
    runs-on: macos-14
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn' # cache packages, but not node_modules
          cache-dependency-path: 'example/yarn.lock'

      - name: Install lib dependencies
        working-directory: lib
        run: yarn install || yarn install

      - name: Build lib
        working-directory: lib
        run: yarn build

      - name: Install Dependencies
        working-directory: example
        run: (yarn || yarn) && yarn rn-setup

      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: example/ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Clean CocoaPods cache
        run: |
          rm -rf ~/Library/Caches/CocoaPods
          pod cache clean --all || true

      - name: Install pods
        working-directory: example
        env:
          COCOAPODS_DISABLE_CHECKSUM: true
        run: |
          gem update cocoapods xcodeproj
          pod install --project-directory=ios || pod install --project-directory=ios

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Build
        working-directory: example
        run: yarn e2e:build:ios-release || yarn e2e:build:ios-release

      - name: Test iOS app
        working-directory: example
        run: yarn e2e:test:ios-release || yarn e2e:test:ios-release

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-videos
          path: ./example/artifacts/
